version: 2.1
commands:
  publish:
    parameters:
      tag:
        type: string
    steps:
        # Allows us to authenticate with the npm registry
      - run: echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > ~/.npmrc
      - run: CI=true npm run release:prep
      - run: TAG=<< parameters.tag >> npm run release:validate
      - run: TAG=<< parameters.tag >> npm run publish

jobs:
  build:
    working_directory: ~/aerogear
    docker:
      - image: circleci/node:lts
    steps:
      - checkout
      - run:
          name: update-npm
          command: 'sudo npm install -g npm@latest'
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: install-dependencies
          command: npm install
      - run:
          name: install-package-dependencies
          command: npm run bootstrap
      - run:
          name: run-build
          command: npm run build
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - ./node_modules
      - run:
          # Hoisting will cache some of the packages, but rest needs to be installed separtely
          name: install-package-dependencies-after-cache
          command: npm run bootstrap
      - run:
          name: run lint
          command: npm run lint
      - run:
          name: test
          command: npm test
      - run:
          name: coverage
          command: npm run coverage
      - store_artifacts:
          path: test-results.xml
          prefix: tests
      - store_artifacts:
          path: coverage
          prefix: coverage
      - store_test_results:
          path: test-results.xml
  npm_publish:
    working_directory: ~/aerogear
    docker:
      - image: circleci/node:lts
    steps:
      - checkout
      - publish:
          tag: "$CIRCLE_TAG"
  npm_publish_master:
    working_directory: ~/aerogear
    docker:
      - image: circleci/node:lts
    steps:
      - checkout
      - run:
          name: version packages
          command: npm run version:master
      - publish:
          tag: "$(node -e \"console.log(require('./lerna.json').version);\")"

workflows:
  version: 2
  build_and_release:
    jobs:
      - build:
          filters:
            tags:
              only: /.*/
      - npm_publish:
          requires:
            - build
          filters:
            tags:
              only: /.*/ # allow anything because tag syntax is validated as part of validate-release.sh
            branches:
              ignore: /.*/
      - npm_publish_master:
          requires:
            - build
          filters:
            branches:
              only: master
            
